export const CONFIG = {
  /**
   * Qualidade gráfica no celular — Android Chrome engasga com bloom +
   * sombras 2048 + DPR 2. Valores aplicados quando `isTouchDevice()`.
   */
  mobileGfx: {
    maxDpr: 1,
    antialias: false,
    shadows: false,
    shadowMapSize: 512,
    bloom: false,
    snowCount: 320,
    grassCount: 900,
    fireflyCount: 28,
    minimapHz: 8,
    /** Neve: atualiza a cada N frames (1 = todo frame). */
    snowFrameSkip: 2,
  },

  // Mundo de inverno: terreno contínuo coberto de neve, lago congelado.
  world: {
    size: 240,
    segments: 200,
    amplitude: 10,
    baseHeight: 2,
    waterLevel: 0,
    treeCount: 130,
    rockCount: 40,
    grassCount: 3200,
    cloudCount: 10,
    fireflyCount: 90,
    birdCount: 4,
    snowCount: 700,
    /** Neve desktop: atualiza a cada N frames (groundHeight/floco foi removido). */
    snowFrameSkip: 2,
    dayLength: 140,
    /** Dias de jogo (ciclos dia/noite) por estação. */
    seasonDays: 2,
    /** Fração final da estação usada na transição gradual do visual. */
    seasonTransition: 0.45,
    seasons: [
      {
        id: "spring",
        label: "Primavera",
        icon: "🌸",
        warmthMul: 0.5,
        snowMul: 0.2,
        iceOpacity: 0.4,
        iceColor: 0x5a9ab8,
        fogTint: 0xa8d4b0,
        /** Cor do solo: neve derretendo, grama nova aparecendo. */
        groundTint: 0x6f9a55,
        groundTintMul: 0.5,
        /** Vegetação: folhas viçosas, grama verde-clara. */
        leafTint: 0x6fae4f,
        leafTintMul: 0.55,
        grassTint: 0x7cb257,
        grassTintMul: 0.6,
      },
      {
        id: "summer",
        label: "Verão",
        icon: "☀️",
        warmthMul: 0.22,
        snowMul: 0,
        iceOpacity: 0.18,
        iceColor: 0x2a6a8a,
        fogTint: 0xb0d0f0,
        /** Campo verde sem neve. */
        groundTint: 0x4d7a38,
        groundTintMul: 0.75,
        leafTint: 0x3f7a30,
        leafTintMul: 0.7,
        grassTint: 0x5aa03a,
        grassTintMul: 0.8,
      },
      {
        id: "autumn",
        label: "Outono",
        icon: "🍂",
        warmthMul: 0.75,
        snowMul: 0.12,
        iceOpacity: 0.55,
        iceColor: 0x7aa8c0,
        fogTint: 0xd4a878,
        /** Solo dourado/marrom de folhas secas. */
        groundTint: 0x9a7038,
        groundTintMul: 0.62,
        /** Folhagem alaranjada/dourada e grama seca. */
        leafTint: 0xc47a2e,
        leafTintMul: 0.72,
        grassTint: 0xb08a3a,
        grassTintMul: 0.7,
      },
      {
        id: "winter",
        label: "Inverno",
        icon: "❄️",
        warmthMul: 1.2,
        snowMul: 1.15,
        iceOpacity: 0.96,
        iceColor: 0xcfe4f2,
        fogTint: 0xb0c8dc,
        /** Whiteout: névoa mais densa + neve mais rápida */
        fogDensityMul: 1.35,
        blizzardMul: 1.3,
        /** Neve pura — sem tinta no solo; pinheiros verdes com neve. */
        groundTint: 0xffffff,
        groundTintMul: 0,
        leafTint: 0x2f4f38,
        leafTintMul: 0.35,
        grassTint: 0xdce8f2,
        grassTintMul: 0.45,
      },
    ],
  },
  player: {
    height: 1.8,
    radius: 0.3,
    eyeHeight: 1.62,
    walkSpeed: 5.2,
    sprintSpeed: 9.0,
    gravity: 24,
    jumpForce: 8.2,
    stepHeight: 2.8,
    attackRange: 2.5,
    attackDamage: 25,
    attackCooldown: 0.55,
  },
  /** FOV e mira (segurar botão direito = ADS). */
  camera: {
    fov: 75,
    fovSprint: 82,
    fovAim: 46,
    fovLerp: 10,
    aimSensMul: 0.48,
    /** Em 3ª pessoa, aproxima a câmera ao mirar. */
    aimDistanceMul: 0.62,
    /** Extra de vignette enquanto mira (0–1). */
    aimVignetteExtra: 0.22,
    /** true = em 3ª pessoa só aproxima câmera (sem FOV); false = zoom FOV também. */
    aimFirstPersonOnly: false,
  },
  survival: {
    maxHealth: 100,
    maxWarmth: 100,
    warmthDrainDay: 0.35,
    warmthDrainNight: 0.7,
    warmthRegen: 22,
    fireRadius: 8,
    coldDamage: 1.2,
    coldMinHealth: 20,
    fireHeal: 3,
  },
  /** Domar montarias: HP abaixo de hpFrac + E (pacifica automaticamente). */
  mountTame: {
    hpFrac: 0.72,
    interactDist: 4.8,
  },
  // legado (referência); stats reais em enemies
  bear: {
    hp: 120,
    wanderSpeed: 1.3,
    chaseSpeed: 6.6,
    aggroRange: 14,
    attackRange: 2.1,
    damage: 18,
    attackCooldown: 1.3,
  },
  // spawnDelay = segundos de jogo antes de aparecer (escalonado, longe da base)
  enemies: {
    bear_minion: {
      label: "Urso jovem",
      hp: 42,
      wanderSpeed: 1.3,
      chaseSpeed: 5.4,
      aggroRange: 10,
      attackRange: 2.0,
      damage: 8,
      attackCooldown: 1.35,
      scale: 0.72,
      color: 0x9a7a58,
      dark: 0x6a5040,
      count: 2,
      mesh: "bear",
      ai: "bear",
      spawnMin: 48,
      spawnDelay: 55,
      spawnStagger: 28,
      faction: "wildlife",
      drops: [
        { weaponId: "axe", chance: 1, name: "Machado", color: 0xb0b8c2 },
        { weaponId: "torch", chance: 0.5, name: "Tocha", color: 0xff9a3c },
        { ammoType: "arrow", amount: 2, chance: 0.22, name: "Flechas", color: 0x9be07a },
      ],
    },
    bear_elite: {
      label: "Urso alfa",
      hp: 150,
      wanderSpeed: 1.0,
      chaseSpeed: 4.6,
      aggroRange: 15,
      attackRange: 2.4,
      damage: 18,
      attackCooldown: 1.55,
      scale: 1.35,
      color: 0x3a2818,
      dark: 0x1e140c,
      count: 1,
      mesh: "bear",
      ai: "bear",
      spawnMin: 70,
      spawnDelay: 140,
      faction: "wildlife",
      dropsTrophy: true,
      drops: [
        { weaponId: "axe", chance: 1, name: "Machado do Alfa", color: 0xd0d8e0 },
        { weaponId: "spear", chance: 1, name: "Lança de gelo", color: 0xa8e8ff },
        { weaponId: "claymore", chance: 0.7, name: "Claymore", color: 0xb8c8d8 },
      ],
    },
    wolf: {
      label: "Lobo da neve",
      hp: 32,
      wanderSpeed: 2.0,
      chaseSpeed: 7.0,
      aggroRange: 13,
      attackRange: 1.7,
      damage: 9,
      attackCooldown: 1.1,
      count: 2,
      mesh: "wolf",
      ai: "wolf",
      spawnMin: 52,
      spawnDelay: 40,
      spawnStagger: 35,
      faction: "wildlife",
      drops: [
        { weaponId: "spear", chance: 1, name: "Lança de gelo", color: 0xa8e8ff },
        { weaponId: "bow", chance: 0.45, name: "Arco", color: 0x9be07a, amount: 4 },
        { ammoType: "arrow", amount: [1, 2], chance: 0.25, name: "Flechas", color: 0x9be07a },
        { trapId: "mine", chance: 0.5, amount: 1, name: "Mina", color: 0x6a6a6a },
      ],
    },
    snow_fox: {
      label: "Raposa-da-neve",
      hp: 22,
      wanderSpeed: 2.4,
      chaseSpeed: 8.2,
      aggroRange: 11,
      attackRange: 1.45,
      damage: 6,
      attackCooldown: 0.95,
      count: 2,
      mesh: "fox",
      ai: "wolf",
      spawnMin: 44,
      spawnDelay: 55,
      spawnStagger: 28,
      faction: "wildlife",
      drops: [
        { ammoType: "arrow", amount: 1, chance: 0.3, name: "Flechas", color: 0x9be07a },
        { trapId: "bait", chance: 0.4, amount: 1, name: "Isca", color: 0xc48a5a },
        { weaponId: "torch", chance: 0.25, name: "Tocha", color: 0xff9a3c },
      ],
    },
    werewolf: {
      label: "Lobisomem",
      hp: 60,
      wanderSpeed: 1.5,
      chaseSpeed: 5.0,
      aggroRange: 13,
      attackRange: 2.1,
      damage: 11,
      attackCooldown: 1.2,
      count: 2,
      mesh: "werewolf",
      ai: "werewolf",
      nightSpeedMul: 1.3,
      nightDamageMul: 1.25,
      spawnMin: 58,
      spawnDelay: 90,
      spawnStagger: 40,
      faction: "occult",
      drops: [
        { weaponId: "ak47", chance: 1, name: "AK-47", color: 0x6a5a3a },
        { ammoType: "bullet", amount: [4, 5], chance: 0.4, name: "Balas", color: 0xd8c25a },
      ],
    },
    mula: {
      label: "Mula sem cabeça",
      hp: 75,
      wanderSpeed: 1.0,
      chaseSpeed: 4.2,
      aggroRange: 11,
      attackRange: 2.2,
      damage: 10,
      attackCooldown: 1.75,
      count: 1,
      mesh: "mula",
      ai: "charger",
      chargeSpeedMul: 1.65,
      chargeInterval: 4.6,
      chargeDuration: 0.7,
      spawnMin: 62,
      spawnDelay: 110,
      faction: "occult",
      // montável (domar com HP <= mountTame.hpFrac + E)
      mount: { seatHeight: 1.55, speed: 7.6, sprint: 10.5, radius: 0.85 },
      drops: [
        { weaponId: "shotgun", chance: 1, name: "Escopeta", color: 0xb87848 },
        { ammoType: "shell", amount: 2, chance: 0.45, name: "Cartuchos", color: 0xe08a5a },
      ],
    },
    // Montarias domáveis (estilo ARK) — enfraqueça e aperte E
    horse: {
      label: "Cavalo selvagem",
      hp: 85,
      wanderSpeed: 1.25,
      chaseSpeed: 5.2,
      aggroRange: 10,
      attackRange: 2.1,
      damage: 9,
      attackCooldown: 1.6,
      count: 1,
      mesh: "horse",
      ai: "charger",
      chargeSpeedMul: 1.6,
      chargeInterval: 4.2,
      chargeDuration: 0.65,
      spawnMin: 50,
      spawnDelay: 95,
      faction: "wildlife",
      mount: { seatHeight: 1.65, speed: 9.2, sprint: 13.0, radius: 0.9 },
      drops: [
        { name: "Poção de vida", color: 0xc42838, healthHeal: 40, chance: 0.55 },
        { ammoType: "arrow", amount: 2, chance: 0.35, name: "Flechas", color: 0x9be07a },
      ],
    },
    dromedary: {
      label: "Dromedário",
      hp: 110,
      wanderSpeed: 0.9,
      chaseSpeed: 3.6,
      aggroRange: 9,
      attackRange: 2.3,
      damage: 11,
      attackCooldown: 1.9,
      scale: 1.15,
      count: 1,
      mesh: "dromedary",
      ai: "charger",
      chargeSpeedMul: 1.35,
      chargeInterval: 5.2,
      chargeDuration: 0.75,
      spawnMin: 58,
      spawnDelay: 130,
      faction: "wildlife",
      mount: { seatHeight: 2.05, speed: 6.0, sprint: 8.2, radius: 1.1 },
      drops: [
        { name: "Poção de vida", color: 0xc42838, healthHeal: 40, chance: 0.6 },
        { trapId: "bait", chance: 0.45, amount: 1, name: "Isca", color: 0xc87840 },
      ],
    },
    pony: {
      label: "Pônei",
      hp: 55,
      wanderSpeed: 1.35,
      chaseSpeed: 4.5,
      aggroRange: 8,
      attackRange: 1.8,
      damage: 6,
      attackCooldown: 1.45,
      scale: 0.78,
      count: 1,
      mesh: "pony",
      ai: "charger",
      chargeSpeedMul: 1.45,
      chargeInterval: 3.8,
      chargeDuration: 0.55,
      spawnMin: 42,
      spawnDelay: 70,
      faction: "wildlife",
      mount: { seatHeight: 1.25, speed: 7.8, sprint: 10.8, radius: 0.7 },
      drops: [
        { name: "Poção menor", color: 0xe05060, healthHeal: 25, chance: 0.7 },
      ],
    },
    slender: {
      label: "Slenderman",
      hp: 80,
      wanderSpeed: 0.55,
      chaseSpeed: 0,
      aggroRange: 18,
      attackRange: 2.6,
      damage: 5,
      attackCooldown: 1.0,
      count: 1,
      mesh: "slender",
      ai: "slender",
      teleportMin: 10,
      teleportMax: 14,
      spawnMin: 65,
      spawnDelay: 160,
      faction: "occult",
      drops: [
        { weaponId: "crossbow", chance: 1, name: "Besta", color: 0x8a9ab0 },
        { weaponId: "grenade", chance: 0.7, name: "Granada", color: 0x5a7a4a, amount: 1 },
        { ammoType: "grenade", amount: 1, chance: 0.35, name: "Granadas", color: 0x5a7a4a },
      ],
    },
    chuck: {
      label: "Chuck",
      hp: 24,
      wanderSpeed: 1.8,
      chaseSpeed: 7.5,
      aggroRange: 12,
      attackRange: 1.5,
      damage: 10,
      attackCooldown: 1.15,
      count: 2,
      mesh: "chuck",
      ai: "chuck",
      spawnMin: 45,
      spawnDelay: 70,
      spawnStagger: 45,
      faction: "chaos",
      drops: [
        { weaponId: "revolver", chance: 1, name: "Revólver", color: 0xd8c25a },
        { ammoType: "bullet", amount: [2, 3], chance: 0.35, name: "Balas", color: 0xd8c25a },
        { ammoType: "arrow", amount: [1, 2], chance: 0.2, name: "Flechas", color: 0x9be07a },
        { trapId: "bait", chance: 0.6, amount: 1, name: "Isca", color: 0xc87840 },
        { trapId: "fence", chance: 0.5, amount: 1, name: "Cerca", color: 0x8a6a40 },
      ],
    },
    // Chefs extras (não substituem o urso alfa). Ordem: panda → saci → trex → boto.
    panda: {
      label: "Panda violento",
      hp: 140,
      wanderSpeed: 0.95,
      chaseSpeed: 4.0,
      aggroRange: 11,
      attackRange: 2.4,
      damage: 12,
      attackCooldown: 1.65,
      scale: 1.4,
      count: 1,
      mesh: "panda",
      ai: "charger",
      chargeSpeedMul: 1.45,
      chargeInterval: 5.0,
      chargeDuration: 0.75,
      spawnMin: 55,
      spawnDelay: 180,
      faction: "wildlife",
      // montável estilo ARK: mais lento que a mula, porém tanque
      mount: { seatHeight: 1.95, speed: 6.2, sprint: 8.6, radius: 1.05 },
      drops: [
        { weaponId: "claymore", chance: 1, name: "Claymore", color: 0xd0d8e8 },
        { weaponId: "shotgun", chance: 0.85, name: "Escopeta", color: 0xb87848 },
        { ammoType: "shell", amount: 2, chance: 0.45, name: "Cartuchos", color: 0xe08a5a },
        { trapId: "mine", chance: 0.7, amount: 2, name: "Minas", color: 0x6a6a6a },
      ],
    },
    saci: {
      label: "Saci-pererê",
      hp: 70,
      wanderSpeed: 2.4,
      chaseSpeed: 8.2,
      aggroRange: 16,
      attackRange: 1.8,
      damage: 12,
      attackCooldown: 0.85,
      count: 1,
      mesh: "saci",
      ai: "saci",
      teleportMin: 2.5,
      teleportMax: 4.5,
      spawnMin: 50,
      spawnDelay: 210,
      faction: "occult",
      drops: [
        { weaponId: "ak47", chance: 1, name: "AK-47", color: 0x6a5a3a },
        { ammoType: "bullet", amount: [4, 5], chance: 0.45, name: "Balas", color: 0xd8c25a },
        { weaponId: "grenade", chance: 0.55, name: "Granada", color: 0x5a7a4a, amount: 1 },
        { trapId: "bait", chance: 0.7, amount: 2, name: "Iscas", color: 0xc87840 },
      ],
    },
    trex: {
      label: "T-Rex gatling",
      hp: 220,
      wanderSpeed: 0.9,
      chaseSpeed: 3.8,
      aggroRange: 22,
      attackRange: 2.8,
      gunRange: 28,
      damage: 9,
      attackCooldown: 0.22,
      burstSize: 5,
      burstGap: 1.35,
      scale: 1.8,
      count: 1,
      mesh: "trex",
      ai: "gunner",
      spawnMin: 65,
      spawnDelay: 250,
      faction: "chaos",
      drops: [
        { weaponId: "ak47", chance: 1, name: "AK-47", color: 0x6a5a3a },
        { weaponId: "revolver", chance: 1, name: "Revólver", color: 0xd8c25a },
        { ammoType: "bullet", amount: [6, 7], chance: 0.5, name: "Balas", color: 0xd8c25a },
        { weaponId: "claymore", chance: 0.75, name: "Claymore", color: 0xd0d8e8 },
      ],
    },
    boto: {
      label: "Boto-cor-de-rosa",
      hp: 200,
      wanderSpeed: 1.2,
      chaseSpeed: 5.6,
      aggroRange: 18,
      attackRange: 2.6,
      damage: 15,
      attackCooldown: 1.25,
      count: 1,
      mesh: "boto",
      ai: "boto",
      spawnMin: 0,
      spawnDelay: 300,
      spawnOnIce: true,
      faction: "occult",
      dropsTrophy: true,
      trophyName: "Troféu do Boto",
      trophySaveId: "win:trophy_boto",
      trophyColor: 0xff7ab8,
      drops: [
        { weaponId: "crossbow", chance: 1, name: "Besta", color: 0x8a9ab0 },
        { ammoType: "arrow", amount: [3, 4], chance: 0.45, name: "Flechas", color: 0x9be07a },
        { weaponId: "spear", chance: 0.9, name: "Lança de gelo", color: 0xa8e8ff },
      ],
    },
    ptero: {
      label: "Pterodáctilo",
      hp: 90,
      wanderSpeed: 3.2,
      chaseSpeed: 7.5,
      aggroRange: 42,
      attackRange: 3.2,
      damage: 12,
      attackCooldown: 1.4,
      count: 2,
      mesh: "ptero",
      ai: "flyer",
      spawnMin: 55,
      spawnDelay: 140,
      faction: "chaos",
      flyHeight: 8,
      drops: [
        { ammoType: "arrow", amount: 3, chance: 0.4, name: "Flechas", color: 0x9be07a },
        { weaponId: "spear", chance: 0.5, name: "Lança de gelo", color: 0xa8e8ff },
      ],
    },
    // Guardião da dungeon secreta — nunca spawna sozinho (count: 0);
    // a SecretDungeon o invoca via spawnEnemyAt. Drop é a Relíquia (via FSM).
    dungeon_boss: {
      label: "Guardião do Abismo",
      hp: 320,
      wanderSpeed: 1.2,
      chaseSpeed: 5.2,
      aggroRange: 40,
      attackRange: 2.6,
      damage: 22,
      attackCooldown: 1.4,
      scale: 1.55,
      color: 0x2a1e3a,
      dark: 0x140c1e,
      count: 0,
      mesh: "bear",
      ai: "bear",
      faction: "abyss",
      drops: [],
    },
  },
  traps: {
    mine: {
      id: "mine",
      name: "Mina",
      icon: "☢",
      triggerRadius: 2.8,
      damage: 70,
      explodeRadius: 5,
      desc: "Explode quando um inimigo chega perto",
    },
    bait: {
      id: "bait",
      name: "Isca",
      icon: "🥩",
      duration: 22,
      lureRadius: 28,
      desc: "Atrai inimigos por ~20s",
    },
    fence: {
      id: "fence",
      name: "Cerca",
      icon: "🧱",
      duration: 45,
      radius: 1.1,
      desc: "Bloqueia inimigos por ~45s",
    },
  },
  trapOrder: ["mine", "bait", "fence"],
  trapPlaceMaxDist: 35,
  trapPickups: [
    { name: "Mina", color: 0x6a6a6a, trapId: "mine", amount: 1 },
    { name: "Mina", color: 0x6a6a6a, trapId: "mine", amount: 1 },
    { name: "Isca de carne", color: 0xc87840, trapId: "bait", amount: 1 },
    { name: "Cerca improvisada", color: 0x8a6a40, trapId: "fence", amount: 1 },
    { name: "Cerca improvisada", color: 0x8a6a40, trapId: "fence", amount: 1 },
  ],
  /** Poções de vida (não contam para vitória). */
  healPickups: [
    { name: "Poção de vida", color: 0xc42838, healthHeal: 40 },
    { name: "Poção de vida", color: 0xc42838, healthHeal: 40 },
    { name: "Poção menor", color: 0xe05060, healthHeal: 25 },
    { name: "Poção menor", color: 0xe05060, healthHeal: 25 },
  ],
  // Personagens default (rostos pixel em /faces/*.png)
  skins: {
    natan: {
      id: "natan",
      name: "Natan",
      face: "faces/natan.png",
      suit: 0x3a2818,
      shirt: 0x5a3a22,
      skin: 0xe8c8a8,
      tie: 0x2a1810,
    },
    jorge: {
      id: "jorge",
      name: "Jorge Bolado",
      face: "faces/jorge.png",
      suit: 0x101010,
      shirt: 0x1a1a1a,
      skin: 0xe8c8a8,
      tie: 0x2a2a2a,
    },
    caio: {
      id: "caio",
      name: "Caio",
      face: "faces/caio.png",
      suit: 0x1a2a1a,
      shirt: 0x3a6a3a,
      skin: 0xf0d8c0,
      tie: 0xe8e8e8,
    },
    lorenzo: {
      id: "lorenzo",
      name: "Lorenzo",
      face: "faces/lorenzo.png",
      suit: 0x4a1010,
      shirt: 0xb02828,
      skin: 0xe8c8a8,
      tie: 0x1a1a1a,
    },
    ze: {
      id: "ze",
      name: "ZÉ",
      face: "faces/ze.png",
      suit: 0x3a2a18,
      shirt: 0x6a4a28,
      skin: 0xf0d4b8,
      tie: 0x2a1a10,
    },
  },
  skinOrder: ["natan", "jorge", "caio", "lorenzo", "ze"],
  /** IDs antigos → personagem (localStorage / saves). */
  skinAlias: {
    classic: "natan",
    arctic: "natan",
    hunter: "jorge",
    night: "caio",
    blaze: "lorenzo",
    ghost: "natan",
    rita: "natan",
    bruno: "natan",
    mega_brain: "natan",
    neymar: "natan",
  },
  weapons: {
    fists: {
      id: "fists",
      name: "Punhos",
      icon: "✊",
      damage: 12,
      range: 2.2,
      cooldown: 0.5,
      slowElite: 0,
      skinColor: 0xf1efe9,
      desc: "Sempre disponíveis",
    },
    axe: {
      id: "axe",
      name: "Machado",
      icon: "🪓",
      damage: 28,
      range: 2.5,
      cooldown: 0.58,
      slowElite: 0,
      skinColor: 0xb0b8c2,
      desc: "Alto dano corpo a corpo",
    },
    spear: {
      id: "spear",
      name: "Lança de gelo",
      icon: "🗡️",
      damage: 22,
      range: 3.2,
      cooldown: 0.52,
      slowElite: 0,
      skinColor: 0xa8e8ff,
      desc: "Maior alcance — boa contra lobos",
    },
    torch: {
      id: "torch",
      name: "Tocha",
      icon: "🔥",
      damage: 16,
      range: 2.4,
      cooldown: 0.5,
      slowElite: 2.2,
      skinColor: 0xff9a3c,
      desc: "Atrasa o urso alfa",
    },
    claymore: {
      id: "claymore",
      name: "Claymore",
      icon: "⚔️",
      damage: 42,
      range: 2.8,
      cooldown: 0.95,
      slowElite: 0,
      skinColor: 0xd0d8e8,
      desc: "Espadona lenta e devastadora",
    },
    bow: {
      id: "bow",
      name: "Arco e flecha",
      icon: "🏹",
      damage: 30,
      range: 60,
      cooldown: 0.8,
      fire: "projectile",
      ammoType: "arrow",
      projSpeed: 34,
      skinColor: 0x6a8a4a,
      desc: "Segure o clique para carregar — solte para atirar",
      chargeable: true,
      chargeMin: 0.12,
      chargeMax: 0.9,
      chargeDmgMin: 0.4,
      chargeDmgMax: 1.3,
      chargeSpeedMin: 0.5,
      chargeSpeedMax: 1.25,
      chargeRangeMin: 0.55,
      chargeRangeMax: 1.2,
    },
    crossbow: {
      id: "crossbow",
      name: "Besta",
      icon: "🎯",
      damage: 45,
      range: 70,
      cooldown: 1.15,
      fire: "projectile",
      ammoType: "arrow",
      projSpeed: 48,
      skinColor: 0x8a9ab0,
      desc: "Segure para tensionar — solte para o tiro pesado",
      chargeable: true,
      chargeMin: 0.18,
      chargeMax: 1.15,
      chargeDmgMin: 0.5,
      chargeDmgMax: 1.35,
      chargeSpeedMin: 0.55,
      chargeSpeedMax: 1.2,
      chargeRangeMin: 0.6,
      chargeRangeMax: 1.15,
    },
    revolver: {
      id: "revolver",
      name: "Revólver",
      icon: "🔫",
      damage: 34,
      range: 50,
      cooldown: 0.55,
      fire: "hitscan",
      ammoType: "bullet",
      magSize: 6,
      skinColor: 0xd8c25a,
      desc: "Preciso · R recarrega (tambor 6)",
    },
    shotgun: {
      id: "shotgun",
      name: "Escopeta",
      icon: "💥",
      damage: 12,
      range: 22,
      cooldown: 1.0,
      fire: "hitscan",
      ammoType: "shell",
      magSize: 2,
      pellets: 5,
      spread: 0.09,
      skinColor: 0xb87848,
      desc: "5 pelotes · R recarrega (2 cartuchos)",
    },
    ak47: {
      id: "ak47",
      name: "AK-47",
      icon: "🪖",
      damage: 14,
      range: 55,
      cooldown: 0.11,
      fire: "hitscan",
      ammoType: "bullet",
      magSize: 30,
      auto: true,
      spread: 0.03,
      skinColor: 0x5a6a3a,
      desc: "Automática · R recarrega (pente 30)",
    },
    grenade: {
      id: "grenade",
      name: "Granada",
      icon: "💣",
      damage: 90,
      range: 30,
      cooldown: 1.2,
      fire: "thrown",
      ammoType: "grenade",
      projSpeed: 16,
      explodeRadius: 6,
      skinColor: 0x5a7a4a,
      desc: "Explode em área após 2s",
    },
    // exclusiva da dungeon secreta — não conta para vitória, é bônus
    relic: {
      id: "relic",
      name: "Relíquia do Abismo",
      icon: "🔮",
      damage: 55,
      range: 3.0,
      cooldown: 0.62,
      slowElite: 1.4,
      skinColor: 0x9a5aff,
      desc: "Lâmina ancestral arrancada do Guardião do Abismo",
    },
  },
  weaponOrder: [
    "fists",
    "axe",
    "spear",
    "torch",
    "claymore",
    "bow",
    "crossbow",
    "revolver",
    "shotgun",
    "ak47",
    "grenade",
    "relic",
  ],
  // munição: reserva + carregador (hitscan). Arco/besta/granada gastam da reserva.
  ammoTypes: {
    arrow: { name: "Flechas", icon: "➶" },
    bullet: { name: "Balas", icon: "•" },
    shell: { name: "Cartuchos", icon: "▮" },
    grenade: { name: "Granadas", icon: "●" },
  },
  // pickups de arma (não contam para vitória) — munição inicial enxuta
  weaponPickups: [
    { name: "Lança de gelo", color: 0xa8e8ff, weaponId: "spear", nearBase: true },
    { name: "Tocha", color: 0xff9a3c, weaponId: "torch", nearBase: true },
    { name: "Claymore enferrujada", color: 0xb8c8d8, weaponId: "claymore", nearBase: true },
    { name: "Arco de caçador", color: 0x9be07a, weaponId: "bow", ammoType: "arrow", amount: 5, nearBase: true },
    { name: "Revólver antigo", color: 0xd8c25a, weaponId: "revolver", ammoType: "bullet", amount: 6, nearBase: true },
    { name: "Escopeta", color: 0xb87848, weaponId: "shotgun", ammoType: "shell", amount: 3, nearBase: true },
    { name: "AK-47", color: 0x6a5a3a, weaponId: "ak47", ammoType: "bullet", amount: 12 },
    { name: "Besta", color: 0x8a9ab0, weaponId: "crossbow", ammoType: "arrow", amount: 4 },
  ],
  // caixas de munição — poucas e pequenas (sobrevivência)
  ammoPickups: [
    { name: "Flechas (+arco)", color: 0x9be07a, ammoType: "arrow", amount: 5 },
    { name: "Balas (+revólver)", color: 0xd8c25a, ammoType: "bullet", amount: 6 },
    { name: "Cartuchos (+escopeta)", color: 0xe08a5a, ammoType: "shell", amount: 2 },
    { name: "Granada", color: 0x5a7a4a, weaponId: "grenade", ammoType: "grenade", amount: 1 },
  ],
  // itens de sobrevivência (+ troféu do urso alfa)
  items: [
    { name: "Lanterna antiga", color: 0xffd75a },
    { name: "Manta térmica", color: 0xc8a070 },
    { name: "Mapa rasgado", color: 0xd8c49a },
    { name: "Bússola", color: 0x7ad0ff },
    { name: "Machado", color: 0xb0b8c2, weaponId: "axe" },
    { name: "Latas de comida", color: 0x9ce09c },
    { name: "Corda", color: 0xd9a066 },
    { name: "Isqueiro", color: 0xff9a3c },
    { name: "Rádio", color: 0xb28aff },
  ],
  thirdPerson: {
    distance: 4.8,
    minDistance: 1.2,
    pivotHeight: 1.5,
    shoulderOffset: 0.85,
  },
  colors: {
    snowLow: 0xe6eef5,
    snowMid: 0xdce8f2,
    snowHigh: 0xf8fbff,
    iceEdge: 0xd8e4ee,
    rock: 0x878c94,
    ice: 0xa9cbe4,
    trunk: 0x4a3626,
    leaf: 0x2d4f38,
    stone: 0x767a80,
    skyDay: 0xa9c6de,
    skyNight: 0x060a16,
    skyDusk: 0xff9a6a,
  },
};
